either/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('questions/',include('question.urls'))
]

question/urls.py
from django.urls import path
from . import views

app_name = 'question'

urlpatterns = [
    path('',views.list,name='list'),
    path('create/',views.create,name='create'),
    path('<int:id>/detail/',views.detail,name='detail'),
    path('<int:id>/comment/create/',views.comment_create,name='comment_create'),
]

question/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    title = models.CharField(max_length=50)
    answerA = models.CharField(max_length=50)
    answerB = models.CharField(max_length=50)
    
    def __str__(self):
        return self.title
        
class Comment(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_list = [['A','left'],['B','right']]
    answer = models.CharField(max_length=100,choices=answer_list )
    content = models.CharField(max_length=100)
    
    def __str__(self):
        return self.content

question/forms.py
from django import forms
from .models import Question,Comment

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = '__all__'
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'

question/views.py
from django.shortcuts import render, resolve_url, redirect
from question.forms import QuestionForm, CommentForm
from .models import Question

# Create your views here.
def list(request):
    # 전체 목록을 보여주는 코드
    questions = Question.objects.all()
    return render(request,'question/list.html',{'questions':questions})
    
def create(request):
    if request.method == "POST":
        # 데이터를 저장
        form = QuestionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(resolve_url('question:list'))
    else:
        # 사용자에게 폼을 전달
        form = QuestionForm()
    return render(request,'question/create.html',{'form':form})
    
def detail(request,id):
    question = Question.objects.get(id=id)
    form = CommentForm(initial={'question':id})
    A = question.comment_set.all().filter(answer="A")
    B = question.comment_set.all().filter(answer="B")
    
    if len(A)+len(B) == 0:
        A_per = 0
        B_per = 0
    else:
        A_per = len(A) / (len(A) + len(B))*100
        B_per = len(B) / (len(A) + len(B))*100
    return render(request,'question/detail.html',{
        'question':question,
        'form':form,
        'A':A,
        'B':B,
        'A_per':A_per,
        'B_per':B_per
    })
    
def comment_create(request,id):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            commnet = form.save(commit=False)
            commnet.question = Question.objects.get(id=id)
            return redirect(resolve_url('question:detail',id))
        pass
    else:
        return redirect(resolve_url('question:detail',id))
    return render(request,'question/detail.html',{'form':form})

question/templates/question/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <a href="{% url 'question:create'%}">글 생성</a>
    <div class="container">
        {%block body%}
        {%endblock%}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

question/templates/question/create.html
{% extends 'question/base.html'%}
{%block body%}
    <form action="{% url 'question:create' %}" method="post">
        {% csrf_token %}
        <table>
        {{form.as_table}}
        </table>
        <input type="submit"/>
    </form>
{%endblock%}

question/templates/question/detail.html
{%extends 'question/base.html'%}

{%block body%}

    <h1>{{question.title}}</h1>
    <h3>{{question.answerA}} : {{A|length}} VS {{question.answerB}} : {{B|length}}</h3>
    <div class="progress">
      <div class="progress-bar" role="progressbar" style="width: {{A_per}}%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100">{{A_per|floatformat}}%</div>
      <div class="progress-bar bg-success" role="progressbar" style="width: {{B_per}}%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">{{B_per|floatformat}}%</div>
    </div>
                        <!--/quetions/1/comment/create-->
    <form action="{% url 'question:comment_create' question.id  %}" method="post">
        {%csrf_token%}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit">
    </form>
    
    <!--댓글을 출력-->
    
    {% for comment in question.comment_set.all %}
        <h5>{{comment.answer}}</h5>
        <p>{{comment.content}}</p>
    {%endfor%}

{%endblock%}

question/templates/question/list.html
{%extends 'question/base.html'%}

{%block body%}
    <h1>여기는 리스트 입니다.</h1>
    {% for q in questions%}
        <h1>{{q.title}}</h1>
        <a href="{% url 'question:detail' id=q.id %}">글보기</a>
    {% endfor %}
{%endblock%}